# This configuration is intended for production use.
name: kafkaemitter
services:
  app:
    image: kafkaemitter
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/kafkaemitter
      - SPRING_DATASOURCE_USERNAME=kafkaemitter
      - SPRING_DATASOURCE_PASSWORD=your-production-password # CHANGE THIS
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/kafkaemitter
    ports:
      - '8086:8080'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
    environment:
      - POSTGRES_USER=kafkaemitter
      - POSTGRES_PASSWORD=kafkaemitter_dt2025
